//-*-C++-*-
/***************************************************************************
 *
 *   Copyright (C) 2025 by Willem van Straten
 *   Licensed under the Academic Free License version 2.1
 *
 ***************************************************************************/

// dspsr/Signal/Generators/dsp/Superposition.h

#ifndef __dsp_Signal_Generators_Superposition_h
#define __dsp_Signal_Generators_Superposition_h

#include "dsp/Generator.h"

namespace dsp {

  //! A superposition (sum) of signals generated by managed Sources
  /*! In principle, can be used to add artifical signals to observational data. */
  class Superposition : public Generator
  {
  protected:

    //! The signals to be superposed (summed)
    std::vector<Reference::To<Source>> sources;

    //! Container used to store output of each source
    Reference::To<TimeSeries> source_output;

  public:

    //! Default constructor
    Superposition ();

    //! Return a copy-constructed clone
    Superposition* clone() const override { return new Superposition(*this); }

    //! Fill the output TimeSeries with the sums of the signals output by all managed Sources
    void operation () override;
    
    //! Add a signal to be superposed
    void add (Source*);
  };

}

#endif // !defined(__dsp_Signal_Generators_Superposition_h)
